### PR TITLE
Autonomous Landing

### PR DESCRIPTION
**Pull request by jeffallen**
Add a goroutine to handle landing.

Add UI to trigger landing (key l).

Adjust the UI to work correctly to receive the current
state from the drone, so that we can watch autonomous
behaviors like landing from the UI.

### CODE REVIEW

**Comment by felixge** [comment]
:sparkling_heart: awesome!

**Comment by jeffallen** [comment]
Yeah, well I forgot to mention that this has not been tested in flight. :)

But I needed it done, at least in nodrone mode, so that I could talk about it tomorrow at the meetup.

I suppose I can test it for the first time in front of the audience there!!!

**Comment by felixge** [comment]
Good luck with the presentation tonight - let me know how it goes!

**Comment by jeffallen** [comment]
The talk went OK.  The audience was amused by your gif.

**Comment by felixge** [comment]
What gif?

**Comment by jeffallen** [comment]
The "testing in production" one. Lol.

**Pull request merged**
